add waiting time and pytest

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -26,24 +26,23 @@ jobs:
         run: docker compose -f ${{ github.workspace }}/test/db/docker-compose.yml down -v
 
       - name: Deploy RAPSQL Containers
-        run: docker compose up -d
+        run: |
+          docker compose up -d
+          sleep 20
 
       - name: Build RAPSQL API Test Container Image
-        run: docker compose -f ${{ github.workspace }}/test/api/docker-compose.yml build
+        run: docker compose -f ${{ github.workspace }}/test/api/docker-compose.yml up --build -d
 
-      - name: Deploy RAPSQL API Test Container
+      - name: Check API Test
         run: |
-          docker compose -f ${{ github.workspace }}/test/api/docker-compose.yml up -d
-
-          CONTAINER_EXIT_CODE=$(docker inspect --format='{{.State.ExitCode}}' rapsql-api-test-container)
-          if [ $CONTAINER_EXIT_CODE -eq 0 ]; then
-            echo "Container exited successfully"
+          CONTAINER_EXIT_CODE=$(docker wait rapsql-api-test-container)
+          echo "Container exit code: $CONTAINER_EXIT_CODE"
+          if [ "$CONTAINER_EXIT_CODE" -ne 0 ]; then
+            echo "Pytest failed. Failing the action."
+            exit 1
           else
-            echo "Container failed to exit successfully"
+            echo "Pytest passed. Continuing the action."
           fi
-  
-          echo "Container logs:"
-          docker logs rapsql-api-test-container
            
       - name: Destroy RAPSQL API Test Container
         run: docker compose -f ${{ github.workspace }}/test/api/docker-compose.yml down
